---
- name: Deploy Docker App on Amazon Linux EC2
  hosts: web
  become: yes
  tasks:
    - name: Install required packages
      yum:
        name:
          - docker
          - git
        state: present
        update_cache: yes

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Verify docker-compose installation
      command: docker-compose --version
      register: compose_version
      ignore_errors: yes

    - debug:
        msg: "Installed Docker Compose Version: {{ compose_version.stdout }}"

    - name: Copy docker-compose file to EC2
      copy:
        src: ./docker-compose.yml
        dest: /home/ec2-user/docker-compose.yml
        owner: ec2-user
        group: ec2-user
        mode: '0644'

    - name: Run docker-compose up
      shell: |
        docker-compose -f /home/ec2-user/docker-compose.yml up -d
      args:
        chdir: /home/ec2-user

